TypeHelp: "&cType \"/bounty help\" for a list of commands."
PlayerNotOnline: "&cThat player is currently not online."
UnknownCmd: "&cUnknown command. Type \"/bounty help\" for a list of commands."
GetPlayerBounty: "&a%player% &chas a bounty of &6%bounty%&c."
NoPerm: "&cYou do not have permission to use this command."
CannotSetPlayerBounty: "&cThis player is ignored from having a bounty."
PlayerBountyCleared: "&a%player% &chas cleared &6%target%&c's bounty."
PlayerBountyAdded: "&a%player% &chas added &e%amount%&c to &6%target%&c's bounty and now has a bounty of &e%bounty%&c."
PlayerBountySet: "&a%player% &chas set &6%target%&c's bounty to &e%amount%&c."
PlayerJoinedWithBounty: "&a%player%&c has joined with a bounty of &e%bounty%&c."
PlayerRetrievedBounty: "&a%player% &chas killed &6%target%&c for a bounty of &e%bounty%&c."
PlayerBountyChanged: "&a%player% &cnow has a bounty of &e%killerbounty%&c."
BountyListHeader: "&6~~~ &cBounty list &6~~~"
BountyListData: "%player%: &c$%amount%"
InvalidAmount: "&cYou do not have that much to set a bounty."
BountyHelpMsg:
  - "&cBounty Commands:"
  - "&c/bounty add <player> <amount>"
  - "&c/bounty set <player> <amount>"
  - "&c/bounty clear <player>"
  - "&c/bounty get <player>"
  - "&c/bounty list [page]"