Header: "&5&l>&d&l> &b&lQubeMC | Faction &d&l<&5&l<"
Footer: "&fOnline &b{playercount} &f- Ping &e{ping}ms"

Colors:
 - Dark_Aqua
 - Dark_Red
 - Dark_Purple
 - Blue
 - Light_Purple
 - Light_Green
 - Aqua
 - Gold
 - White
 - Dark_Blue
 - Green
 - Light_Gray
 - Dark_Gray
 - Red
 - Yellow
 - Black
 
Scoreboard:
  Title: '&b&lFactions &b({playercount}/&9{bungeecount}&b/100)'
  Fifteen: 'Prefix%P|Test%S|Suffix'
  Fourteen: ''
  Thirteen: ''
  Twelve: ''
  Eleven: ''
  Ten: ''
  Nine: ''
  Eight: ''
  Seven: ''
  Six: ''
  Five: ''
  Four: ''
  Three: ''
  Two: ''
  One: ''
  